import Head from 'next/head'
import styles from '../styles/Home.module.css'
import data from '../ulink/links.json';
import Image from 'next/image'
const pti = data.img
import img from {pti}

export default function Home() {

const links = data.links
const linkItems = links.map((thing) =>
	<div key={thing.id.toString()}>
  	<a 
			className="link" 
			href={thing.url}>
			{thing.title}
		</a>
	</div>
);

	
  return (
    <div>
      <Head>
        <title>{data.display + " | Ulink Flash"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
			<link
  			href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
  			rel="stylesheet"
			/>
      </Head>

      <main className={styles.main}>
    <div id="head">    
    </div>
    <center id="social"></center>
		<div id="head">
		<div className="center-img">
    <Image
      src={img}
      alt="Picture of the user"
      width={100}
      height={100}
    />			
			</div>
			<a href="https://instagram.com/benmmonster" className="h1" id="h1">{data.name}</a><p>{data.symbol + data.user}</p>
		</div>
    <div id="links" className="link-cont">{linkItems}</div>
    <p id="Attribution" className="atr"></p>
		</main>
    </div>
  )
}