import Head from 'next/head'
import styles from '../styles/Home.module.css'
import data from '../public/links.json';

export default function Home() {

const links = data.links
const linkItems = links.map((thing) =>
	<div key={thing.id.toString()}>
  	<a 
			className="link" 
			href={thing.url}>
			{thing.title}
		</a>
	</div>
);

	
  return (
    <div>
      <Head>
        <title>{data.display + " | Ulink Flash"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    <div id="head">    
    </div>
    <center id="social"></center>
		<div id="head">    
    	<img src={data.photo}></img>
			<a href="https://instagram.com/benmmonster" className="h1" id="h1">{data.name}</a><p>{data.symbol + data.user}</p>
		</div>
    <div id="links" className="link-cont">{linkItems}</div>
    <p id="Attribution" className="atr"></p>
		<link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet"/>
	
	</main>


    </div>
  )
}
